/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import BD.Conexion;
import Logica.Core;
import Logica.Student;
import Logica.User;
import Main.Main;
import Register.Register;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ji_rq
 */
public class LoginClassHub extends javax.swing.JFrame {

    /**
     * Creates new form LoginClassHub
     */
    public LoginClassHub() {
        initComponents();
        SetIcon();
        this.setLocationRelativeTo(null);
        Core.getInstance().pullAllStudents();
        Core.getInstance().pullAllTeachers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        IngresarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NewAccountLabel = new javax.swing.JLabel();
        UsuarioField = new javax.swing.JTextField();
        sep1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        NewAccountLabel1 = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClassHub");
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IngresarButton.setBackground(new java.awt.Color(84, 127, 255));
        IngresarButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        IngresarButton.setForeground(new java.awt.Color(255, 255, 255));
        IngresarButton.setText("Ingresar");
        IngresarButton.setActionCommand("IngresarButton");
        IngresarButton.setBorder(null);
        IngresarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IngresarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarButtonMouseClicked(evt);
            }
        });
        jPanel2.add(IngresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 310, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html><body>Ingresa tus datos en el formulario <br> y lleva seguimiento de tu universidad</body></html>");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 320, 40));

        NewAccountLabel.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        NewAccountLabel.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        NewAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NewAccountLabel.setText("Aun no tienes cuenta?");
        NewAccountLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NewAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewAccountLabelMouseEntered(evt);
            }
        });
        jPanel2.add(NewAccountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 140, -1));

        UsuarioField.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        UsuarioField.setForeground(new java.awt.Color(196, 196, 196));
        UsuarioField.setText("Usuario");
        UsuarioField.setBorder(null);
        UsuarioField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsuarioFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsuarioFieldFocusLost(evt);
            }
        });
        jPanel2.add(UsuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 310, 30));

        sep1.setBackground(new java.awt.Color(215, 215, 215));
        jPanel2.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 310, -1));

        jSeparator2.setBackground(new java.awt.Color(215, 215, 215));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 310, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 28)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Bienvenido Estudiante!");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 320, 40));

        NewAccountLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        NewAccountLabel1.setForeground(new java.awt.Color(57, 123, 255));
        NewAccountLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NewAccountLabel1.setText("Crear Cuenta");
        NewAccountLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewAccountLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewAccountLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NewAccountLabel1MouseEntered(evt);
            }
        });
        jPanel2.add(NewAccountLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 90, -1));

        PassField.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        PassField.setForeground(new java.awt.Color(196, 196, 196));
        PassField.setText("Contraseña");
        PassField.setBorder(null);
        PassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PassFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PassFieldFocusLost(evt);
            }
        });
        jPanel2.add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 322, 310, 30));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(450, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 570));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 460, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewAccountLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewAccountLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAccountLabelMouseEntered

    private void UsuarioFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuarioFieldFocusGained
        if (UsuarioField.getText().equals("Usuario")) {
            UsuarioField.setText("");
            UsuarioField.setForeground(Color.black);

        }
    }//GEN-LAST:event_UsuarioFieldFocusGained

    private void UsuarioFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuarioFieldFocusLost
        if (UsuarioField.getText().equals("")) {
            UsuarioField.setText("Usuario");
            UsuarioField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_UsuarioFieldFocusLost

    private void NewAccountLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewAccountLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAccountLabel1MouseEntered

    private void IngresarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarButtonMouseClicked

        String user = UsuarioField.getText();
        String pass = new String(PassField.getPassword());

        String query = "SELECT idUsuario, usuario, pass, idEstudiante FROM Usuario WHERE usuario = '" + user + "' ";
        try {
            Connection con = Conexion.getConexion();
            PreparedStatement ps = con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String u = rs.getString("usuario");
                String p = rs.getString("pass");
                String i = rs.getString("idUsuario");
                String e = rs.getString("idEstudiante");

                if (pass.equals(p)) {
                    User aux = new User(i, u, p, e);
                    Core.getInstance().addUser(aux);
                    if (Core.getInstance().validate(u, p)) {
                        System.out.println("Usuario activo ahora es " + Core.getLoggedUser().getUsername());
                        
                        Student userStudentData = Core.getInstance().getDataUserStudentLogged(Core.getLoggedUser().getIdStudent());
                        Core.getInstance().pullAllSubjects(userStudentData.getIdCarrera());
                        Core.getInstance().pullPeriodosByIdStudent(userStudentData.getId());
                        Core.getInstance().pullSubjectsXPeriodActive(userStudentData.getId());
                        
                        dispose();
                        Main main = new Main();
                        main.setVisible(true);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "La contraseña es incorrecta!", "Advertencia", JOptionPane.WARNING_MESSAGE);
                    PassField.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Este Usuario no existe, revisa tus credenciales!", "Error al ingresar", JOptionPane.ERROR_MESSAGE);
                UsuarioField.setText("");
                PassField.setText("");
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
//       

    }//GEN-LAST:event_IngresarButtonMouseClicked

    private void NewAccountLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewAccountLabel1MouseClicked

        dispose();
        Register register = new Register();
        register.setVisible(true);
    }//GEN-LAST:event_NewAccountLabel1MouseClicked

    private void PassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassFieldFocusGained
        String valorPass = new String(PassField.getPassword());
        if (valorPass.equals("Contraseña")) {
            PassField.setText("");
            PassField.setForeground(Color.black);

        }
    }//GEN-LAST:event_PassFieldFocusGained

    private void PassFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PassFieldFocusLost
        String valorPass = new String(PassField.getPassword());
        if (valorPass.equals("")) {
            PassField.setText("Contraseña");
            PassField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PassFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginClassHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginClassHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginClassHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginClassHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginClassHub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarButton;
    private javax.swing.JLabel NewAccountLabel;
    private javax.swing.JLabel NewAccountLabel1;
    private javax.swing.JPasswordField PassField;
    public javax.swing.JTextField UsuarioField;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator sep1;
    // End of variables declaration//GEN-END:variables

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/logoClassHub.png")));
    }
}
